In [1]:
import pandas as pd
import numpy as np

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [2]:
print(f"Using the PyTorch version: {torch.__version__}")

## getting the device
device = "cuda" if torch.cuda.is_available() else 'cpu'
print(f"Device:{device}")

Using the PyTorch version: 2.8.0+cu128
Device:cuda

In [3]:
## Reading the Data

df = pd.read_csv('/home/prashant/Documents/ML-DL/PyTorch/100_Unique_QA_Dataset.csv')
print('-'*5,'First 10 rows','-'*5,'\n')
display(df.head(10))
print(f'Shape of the Dataset:{df.shape}')

----- First 10 rows -----

                                          question             answer
0                   What is the capital of France?              Paris
1                  What is the capital of Germany?             Berlin
2               Who wrote 'To Kill a Mockingbird'?         Harper-Lee
3  What is the largest planet in our solar system?            Jupiter
4   What is the boiling point of water in Celsius?                100
5                       Who painted the Mona Lisa?  Leonardo-da-Vinci
6                   What is the square root of 64?                  8
7            What is the chemical symbol for gold?                 Au
8                 Which year did World War II end?               1945
9          What is the longest river in the world?               Nile

Shape of the Dataset:(90, 2)

In [21]:
# Tokenization

def tokenize(text):
    text = text.lower()
    text = text.replace('?','')
    text = text.replace("'","")

    tokens = text.split()

    return tokens

In [22]:
tokenize('What is the name of longest river in the world?')

['what', 'is', 'the', 'name', 'of', 'longest', 'river', 'in', 'the', 'world']

In [27]:
# Creating a vocabulary

vocab = {'<UNK>':0}

In [33]:
def update_vocab(row):

    question, answer = tokenize(row['question']), tokenize(row['answer'])

    qa = question + answer

    for word in qa: 
        if word not in vocab:
            vocab[word] = len(vocab)

    return row

In [34]:
df.apply(update_vocab, axis=1)

                                             question        answer
0                      What is the capital of France?         Paris
1                     What is the capital of Germany?        Berlin
2                  Who wrote 'To Kill a Mockingbird'?    Harper-Lee
3     What is the largest planet in our solar system?       Jupiter
4      What is the boiling point of water in Celsius?           100
..                                                ...           ...
85                  Who directed the movie 'Titanic'?  JamesCameron
86  Which superhero is also known as the Dark Knight?        Batman
87                     What is the capital of Brazil?      Brasilia
88        Which fruit is known as the king of fruits?         Mango
89       Which country is known for the Eiffel Tower?        France

[90 rows x 2 columns]

In [43]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299,792,458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'longest-running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 'earths': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second-largest': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net,': 265,
 'ball,': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}

In [41]:
def find_index(sentence, vocab):

    indexes = []

    for token in tokenize(sentence):
        if token in vocab:
            indexes.append(vocab[token])
        else:
            indexes.append(vocab['<UNK>'])
    return indexes

In [44]:
find_index('Paris is the capital of France.', vocab)

[7, 2, 3, 4, 5, 0]

In [45]:
## Creating the custom dataset class

class CustomDataset(Dataset):

    def __init__(self, df, vocab):
        self.df = df
        self.vocab = vocab

    def __len__(self):
        return len(self.df)

    def __getitem__(self, index):

        question = find_index(self.df.iloc[index]['question'], self.vocab)
        answer = find_index(self.df.iloc[index]['answer'], self.vocab)

        return torch.tensor(question), torch.tensor(answer)

In [46]:
data = CustomDataset(df, vocab)

In [72]:
dataloader = DataLoader(data, batch_size=1, shuffle=True)

In [61]:
len_list = []
for i in range(len(data)):
    q, a = data[i]
    question_len = len(q.tolist())
    len_list.append(question_len)

print(f"Max number of tokens available in questions: {max(len_list)}")

Max number of tokens available in questions: 12

In [62]:
# Check the data
for i in range(5):
    question, answer = data[i]
    print(f"Question Tensor: {question}")
    print(f"Answer Tensor: {answer}")
    print('-'*20)

Question Tensor: tensor([1, 2, 3, 4, 5, 6])
Answer Tensor: tensor([7])
--------------------
Question Tensor: tensor([1, 2, 3, 4, 5, 8])
Answer Tensor: tensor([9])
--------------------
Question Tensor: tensor([10, 11, 12, 13, 14, 15])
Answer Tensor: tensor([16])
--------------------
Question Tensor: tensor([ 1,  2,  3, 17, 18, 19, 20, 21, 22])
Answer Tensor: tensor([23])
--------------------
Question Tensor: tensor([ 1,  2,  3, 24, 25,  5, 26, 19, 27])
Answer Tensor: tensor([28])
--------------------

In [85]:
## Model Building

class SimpleRNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=50)
        self.rnn = nn.RNN(50, 64,batch_first=True)
        self.fc = nn.Linear(64, vocab_size)

    def forward(self, question):
        embeded_question = self.embedding(question)
        hidden, final = self.rnn(embeded_question)
        output = self.fc(final.squeeze(0))
        
        return output

In [86]:
learning_rate = 0.001
epochs = 20

model = SimpleRNN(len(vocab)).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
for epoch in range(epochs):

    total_loss = 0

    for ques, ans in dataloader:

        ques, ans = ques.to(device), ans.to(device)

        optimizer.zero_grad()

        # prediction
        y_pred = model(ques)

        # loss
        loss = criterion(y_pred, ans[0])

        # backpropagation
        loss.backward()

        # update the weights
        optimizer.step()

        ## Update the total loss
        total_loss += loss.item()

    print(f"Epoch: {epoch+1:<2}/{epochs}, Loss: {total_loss:4f}")

Epoch: 1 /20, Loss: 0.525493
Epoch: 2 /20, Loss: 0.498792
Epoch: 3 /20, Loss: 0.473763
Epoch: 4 /20, Loss: 0.449913
Epoch: 5 /20, Loss: 0.427259
Epoch: 6 /20, Loss: 0.406031
Epoch: 7 /20, Loss: 0.385618
Epoch: 8 /20, Loss: 0.366851
Epoch: 9 /20, Loss: 0.348844
Epoch: 10/20, Loss: 0.332101
Epoch: 11/20, Loss: 0.315897
Epoch: 12/20, Loss: 0.300285
Epoch: 13/20, Loss: 0.285935
Epoch: 14/20, Loss: 0.272147
Epoch: 15/20, Loss: 0.259249
Epoch: 16/20, Loss: 0.246903
Epoch: 17/20, Loss: 0.235020
Epoch: 18/20, Loss: 0.223800
Epoch: 19/20, Loss: 0.213397
Epoch: 20/20, Loss: 0.203430

In [106]:
def predict(model=model, question=' ', thresold=0.5):

    question_array = find_index(question, vocab)
    question_tensor = torch.tensor(question_array).unsqueeze(0).to(device)

    output = model(question_tensor)

    probabilities = torch.nn.functional.softmax(output, dim=1)

    value, index = torch.max(probabilities, dim=1)

    print(f"Question: {question}", \
          f"Answer: {list(vocab.keys())[index.item()].upper() if value.item() > thresold else "I don't know"}", \
            sep='\n')

In [108]:
def get_question():
    question = input("Ask a question: ")
    return question

predict(question=get_question())

Question: How many animals are carnivores?
Answer: I don't know