In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

### train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 1.17922559, -0.1250568 ,  1.18538033, ...,  0.28404587,
         0.14107906, -0.24476486],
       [-0.2017801 , -0.53421355, -0.26167261, ..., -0.674194  ,
        -0.28874379, -0.4646623 ],
       [-0.1416118 ,  1.27542829, -0.16692015, ...,  0.29016587,
         0.83033069, -0.29200208],
       ...,
       [-0.41093657, -0.4523822 , -0.43746336, ..., -0.88609919,
        -0.37010311, -0.84147421],
       [-0.53127316,  0.74936962, -0.56504672, ..., -0.77395009,
         0.2623505 , -0.12748622],
       [-1.33752835, -0.21390227, -1.32805339, ..., -0.97024926,
        -0.7293122 , -0.16386432]])

In [ ]:
y_train

53     M
364    B
126    M
17     M
285    B
      ..
179    B
16     M
325    B
490    B
359    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0])

### Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [ ]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float())

  # loss calculate
  loss = model.loss_function(y_pred.float(), y_train_tensor.float())

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7111450433731079
Epoch: 2, Loss: 0.7006419897079468
Epoch: 3, Loss: 0.6941612362861633
Epoch: 4, Loss: 0.6899022459983826
Epoch: 5, Loss: 0.6868845224380493
Epoch: 6, Loss: 0.6845898628234863
Epoch: 7, Loss: 0.6827439069747925
Epoch: 8, Loss: 0.6811969876289368
Epoch: 9, Loss: 0.6798638701438904
Epoch: 10, Loss: 0.6786926984786987
Epoch: 11, Loss: 0.677649736404419
Epoch: 12, Loss: 0.6767117381095886
Epoch: 13, Loss: 0.6758614778518677
Epoch: 14, Loss: 0.6750861406326294
Epoch: 15, Loss: 0.6743751764297485
Epoch: 16, Loss: 0.6737204194068909
Epoch: 17, Loss: 0.6731148958206177
Epoch: 18, Loss: 0.6725531220436096
Epoch: 19, Loss: 0.6720302700996399
Epoch: 20, Loss: 0.6715424060821533
Epoch: 21, Loss: 0.6710858941078186
Epoch: 22, Loss: 0.6706580519676208
Epoch: 23, Loss: 0.6702561378479004
Epoch: 24, Loss: 0.6698778867721558
Epoch: 25, Loss: 0.6695213913917542

In [ ]:
model.linear.weight, model.linear.bias

(Parameter containing:
 tensor([[-0.0416, -0.1301,  0.1178,  0.0388, -0.0412,  0.0999,  0.0649, -0.0943,
           0.0194, -0.1748,  0.1227, -0.1007,  0.0158, -0.1295,  0.1391,  0.0326,
           0.1060, -0.0403, -0.1145, -0.0210, -0.1275,  0.1485,  0.0285, -0.1207,
           0.0161, -0.0166, -0.0239,  0.0316,  0.1110, -0.0410]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.3321], requires_grad=True))

### Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6292705535888672

## Now using the Built-in Loss Function and Optimizer

In [ ]:
class MySimpleNN_(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# Creating Optimizer object
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor.float())

  # loss calculate
  loss = loss_function(y_pred.float(), y_train_tensor.view(-1,1).float())

  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # calling optimizer
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7501020431518555
Epoch: 2, Loss: 0.558052122592926
Epoch: 3, Loss: 0.45938941836357117
Epoch: 4, Loss: 0.39982694387435913
Epoch: 5, Loss: 0.35935595631599426
Epoch: 6, Loss: 0.32967478036880493
Epoch: 7, Loss: 0.3067401349544525
Epoch: 8, Loss: 0.28833696246147156
Epoch: 9, Loss: 0.2731439769268036
Epoch: 10, Loss: 0.2603205740451813
Epoch: 11, Loss: 0.24930451810359955
Epoch: 12, Loss: 0.23970428109169006
Epoch: 13, Loss: 0.23123802244663239
Epoch: 14, Loss: 0.22369728982448578
Epoch: 15, Loss: 0.2169240564107895
Epoch: 16, Loss: 0.21079611778259277
Epoch: 17, Loss: 0.20521733164787292
Epoch: 18, Loss: 0.20011074841022491
Epoch: 19, Loss: 0.19541403651237488
Epoch: 20, Loss: 0.1910758912563324
Epoch: 21, Loss: 0.1870538294315338
Epoch: 22, Loss: 0.18331210315227509
Epoch: 23, Loss: 0.1798204630613327
Epoch: 24, Loss: 0.17655307054519653
Epoch: 25, Loss: 0.17348770797252655

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5392428636550903