In [ ]:
import torch
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
# getting data
data_url = "https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv"
df = pd.read_csv(data_url)
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
# Checking null entries
df.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [ ]:
cols = df.columns
print("Dropping columns:",cols[0], '&',cols[-1])

Dropping columns: id & Unnamed: 32

In [ ]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [ ]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [ ]:
## Checking the target column
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

* 'B' stands for **Benign:** A `benign` breast lump is `not cancer`. It is made of abnormal but `non-cancerous` cells that do not invade nearby tissue or spread to other parts of the body (no metastasis). Benign lumps can still grow or cause pain/pressure, and sometimes doctors remove them, but they are generally not life-threatening.

* 'M' stands for **Malignant:** A `malignant` breast lump is `cancer`. These cells grow in an uncontrolled way, can invade surrounding breast tissue, and may spread to other parts of the body through blood or lymph vessels (metastasis). `Malignant tumors usually need active treatment (such as surgery, chemotherapy, radiation, or hormonal therapy).`

In [ ]:
# Splitting Dataset
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2, random_state=42)

print("Shape of the splitted dataset:", [X_train.shape, X_test.shape, y_train.shape, y_test.shape])

Shape of the splitted dataset: [(455, 30), (114, 30), (455,), (114,)]

In [ ]:
## Scaling the dataset
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train[0] ## First row of Train set

array([-1.44075296, -0.43531947, -1.36208497, -1.1391179 ,  0.78057331,
        0.71892128,  2.82313451, -0.11914956,  1.09266219,  2.45817261,
       -0.26380039, -0.01605246, -0.47041357, -0.47476088,  0.83836493,
        3.25102691,  8.43893667,  3.39198733,  2.62116574,  2.06120787,
       -1.23286131, -0.47630949, -1.24792009, -0.97396758,  0.72289445,
        1.18673232,  4.67282796,  0.9320124 ,  2.09724217,  1.88645014])

In [ ]:
X_test[0] ## First row of Test set

array([-0.46649743, -0.13728933, -0.44421138, -0.48646498,  0.28085007,
        0.04160589, -0.11146496, -0.26486866,  0.41524141,  0.13513744,
       -0.02091509, -0.29323907, -0.17460869, -0.2072995 , -0.01181432,
       -0.35108921, -0.1810535 , -0.24238831, -0.33731758, -0.0842133 ,
       -0.2632354 , -0.14784208, -0.33154752, -0.35109337,  0.48001942,
       -0.09649594, -0.03583041, -0.19435087,  0.17275669,  0.20372995])

In [ ]:
## Labelling the Traget Column using Label encoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [ ]:
le.classes_

array(['B', 'M'], dtype=object)

In [ ]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [ ]:
# Converting the numpy array to pytorch tensor

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

## Defining the ANN Model using PyTorch

In [ ]:
class SimpleNN():
  ## Defining Constructor
  def __init__(self, X):

    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  # Forward training function
  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_hat = torch.sigmoid(z)
    return y_hat

  # Function for calculating Loss
  def loss_function(self, y_hat, y):
    # Clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_hat = torch.clamp(y_hat, epsilon, 1-epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_hat) + (1-y_train_tensor) * torch.log(1-y_hat)).mean()
    return loss

## Defining trainning parameters & model

In [ ]:
learning_rate = 0.1
epochs = 50

## Create model
model = SimpleNN(X_train_tensor)

## Define loop
for epoch in range(epochs):

  # Forward pass
  y_pred = model.forward(X_train_tensor)

  # Calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward pass
  loss.backward()

  # Update Parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # Zero Gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.385490157016557
Epoch: 2, Loss: 3.2443338526353394
Epoch: 3, Loss: 3.094648144785665
Epoch: 4, Loss: 2.9369189233277178
Epoch: 5, Loss: 2.777099264216911
Epoch: 6, Loss: 2.616281443925772
Epoch: 7, Loss: 2.450553003955021
Epoch: 8, Loss: 2.283036309956344
Epoch: 9, Loss: 2.112290934750733
Epoch: 10, Loss: 1.938533176396359
Epoch: 11, Loss: 1.7658836580244688
Epoch: 12, Loss: 1.5999016762995315
Epoch: 13, Loss: 1.4455367545854558
Epoch: 14, Loss: 1.3051537695586188
Epoch: 15, Loss: 1.1811991737324083
Epoch: 16, Loss: 1.075795308384266
Epoch: 17, Loss: 0.9900378895917769
Epoch: 18, Loss: 0.9233353706103844
Epoch: 19, Loss: 0.8733372032168479
Epoch: 20, Loss: 0.83663631073996
Epoch: 21, Loss: 0.8098042287170185
Epoch: 22, Loss: 0.7900055977919629
Epoch: 23, Loss: 0.7751230854215891
Epoch: 24, Loss: 0.7636672878865264
Epoch: 25, Loss: 0.7546267450044802
Epoch: 26, Loss: 0.7473240499302778
Epoch: 27, Loss: 0.7413036528244642
Epoch: 28, Loss: 0.7362537837148622
Epoch: 29, Loss: 0.7319554631312118
Epoch: 30, Loss: 0.728250301400349
Epoch: 31, Loss: 0.7250204370367467
Epoch: 32, Loss: 0.7221760041472515
Epoch: 33, Loss: 0.7196471640600188
Epoch: 34, Loss: 0.7173788817558854
Epoch: 35, Loss: 0.7153273646732492
Epoch: 36, Loss: 0.7134575316011964
Epoch: 37, Loss: 0.7117411441806782
Epoch: 38, Loss: 0.7101553852110416
Epoch: 39, Loss: 0.7086817534563463
Epoch: 40, Loss: 0.7073051926710822
Epoch: 41, Loss: 0.7060133998837957
Epoch: 42, Loss: 0.7047962740290455
Epoch: 43, Loss: 0.7036454759611698
Epoch: 44, Loss: 0.7025540774697954
Epoch: 45, Loss: 0.7015162815909888
Epoch: 46, Loss: 0.7005272000225797
Epoch: 47, Loss: 0.6995826762049071
Epoch: 48, Loss: 0.698679144836914
Epoch: 49, Loss: 0.6978135203906736
Epoch: 50, Loss: 0.6969831086488499

In [ ]:
# Checking Bias
model.bias

tensor([-0.3361], dtype=torch.float64, requires_grad=True)

In [ ]:
# Checking weights
model.weights

tensor([[ 0.3761],
        [-0.1871],
        [ 0.1086],
        [-0.0192],
        [-0.1200],
        [-0.0728],
        [-0.1150],
        [-0.4790],
        [-0.0885],
        [-0.0651],
        [-0.1396],
        [ 0.3684],
        [-0.1187],
        [ 0.2367],
        [-0.1576],
        [ 0.0684],
        [-0.2805],
        [ 0.1228],
        [ 0.0049],
        [ 0.4474],
        [ 0.3463],
        [-0.0064],
        [ 0.2769],
        [-0.3534],
        [ 0.4369],
        [ 0.2387],
        [-0.2969],
        [-0.2003],
        [ 0.2291],
        [ 0.0491]], dtype=torch.float64, requires_grad=True)

## Evaluation

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  print(f"Predicted Array:\n{y_pred}")
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Predicted Array:
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.]])
Accuracy: 0.5689442753791809